version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Europe/Brussels
    open-pull-requests-limit: 99
    commit-message:
      prefix: ""
    labels:
      - "dependencies"
