#!/bin/bash

debug() { echo -n "$@" " - " >&2; date >&2; }
debug start

set -o pipefail -e

# Temp files
config="$(mktemp)"      # configuration
result="$(mktemp)"      # result json
compilation="$(mktemp)" # output of compilation
execution="$(mktemp)"   # output of execution
mkdir "/tmp/build"      # compilation directory

trap "rm -rf '$config' '$result' '$compilation' '$execution' '/tmp/build'" EXIT

# Saving the configuration from stdin
cat > "$config"

# Directories containing the test files and the judge repository
resources="$(jshon -e 'resources' -u < "$config")"
judge="$(jshon -e 'judge' -u < "$config")"
workdir="$(jshon -e 'workdir' -u < "$config")"
filename="$(jshon -e 'filename' -u < "$config")"

# time and memory limit with margins
time_limit="$(jshon -e 'time_limit' -u < "$config")"
time_limit="$(( time_limit - 10 ))"

memory_limit="$(jshon -e 'memory_limit' -u < "$config")"
memory_limit="$(( memory_limit * 9 / 10000 ))"

# Other configuration parameters.
allow_compilation_warnings="$(jshon -Q -e 'allow_compilation_warnings' -u < "$config" || echo 'true')"

############################## [ Helper functions ] ############################
# Import json helper functions.
dodona() { "$judge/dodona" "$@"; }

compilation_error_count() {
    tail -n2 | sed -n 's/^\([0-9]\+\) errors\?$/\1/p'
}

compilation_warning_count() {
    tail -n2 | sed -n 's/^\([0-9]\+\) warnings\?$/\1/p'
}

explain_compilation_error() {
    case "$1" in
        *"should be declared in a file named"*)
            # Wrong class name.
            expected_class_name="${filename%.java}"
            echo "De naam van je klasse hoort \"$expected_class_name\" te zijn."
            ;;
        *"cannot find symbol"*)
            # Cannot find symbol - forgotten import.
            class_name="$(echo "$1" | sed -n '/symbol: *class/s/.*class \(\S\+\)\s*.*/\1/p')"
            [ -z "$class_name" ] || echo "Je probeert een onbekende klasse \"$class_name\" te gebruiken. Mogelijks ben je de noodzakelijke import vergeten."
            ;;
        *"assign a value to final variable"*)
            # Assignment to final variable.
            variable_name="$(echo "$1" | grep -o "final variable \S\+" | sed "s/final variable //" | sed "s/\\\n//")"
            echo "Variabelen die als \"final\" zijn gedeclareerd, kunnen niet meer worden aangepast eens ze een waarde hebben. Verwijder het keyword \"final\" bij de variabele \"$variable_name\" om dit op te lossen."
            ;;
    esac
}

explain_compilation_warning() {
    case "$1" in
        *"found raw type"*)
            echo "Het is aangeraden een type mee te geven aan generieke klassen."
            ;;
    esac
}

parse_compilation_error_staff() {
    # arg1: 1 compiler log
    dodona start-context
    dodona start-testcase -d "Compilatiefout"
    dodona append-message -f code -p staff -d "$1"
    dodona close-testcase -A
    dodona close-context
}

parse_compilation_error_student() {
    # arg1: 1 compiler log
    dodona start-context

    # Determine the kind of compilation message.
    if echo "$1" | grep -q "^$filename:[0-9]\+: warning:"; then
        # warning
        type='warning'
        explanation="$(explain_compilation_warning "$1")"
        testcase_msg='Compilatiewaarschuwing'
    else
        # error
        type='error'
        explanation="$(explain_compilation_error "$1")"
        testcase_msg='Compilatiefout'
    fi

    # Start the case, add the explanation message if it exists, add compilation output as message
    [ -z "$explanation" ] || testcase_msg+=": $explanation"
    dodona start-testcase -d "$testcase_msg"
    dodona append-message -f code -d "$1"

    # Get the code annotation information.
    annotation_column="$(echo "$1" | grep -o "\s*\^" | wc -c)"
    annotation_column="$((annotation_column - 2))"
    annotation_row="$(echo "$1" | sed -n "s/^$filename:\([0-9]\+\):.*/\1/p")"
    annotation_row="$((annotation_row - 1))"

    if [ -z "$explanation" ]; then
        # Use the first line of the compilation log.
        explanation="$(echo "$1" | sed 's/.*: \(error\|warning\): //' | head -n 1)"
    fi

    # Annotate the code accordingly.
    dodona annotate-code -r "$annotation_row" -c "$annotation_column" -t "$type" -m "$explanation"

    dodona close-testcase -A
    dodona close-context
}

parse_compilation_errors() {
    # arg1: permission
    # reads log from stdin

    # Loop over the compile log and process each message individually.
    compile_err=""
    while IFS= read -r line; do
        if echo "$line" | egrep -q "^$filename:[0-9]+:"; then
            if [ -n "$compile_err" ]; then
                if [ "$1" = 'student' ]; then
                    parse_compilation_error_student "$compile_err" </dev/zero
                else
                    parse_compilation_error_staff "$compile_err" </dev/zero
                fi
            fi
            compile_err="$line"
        else
            compile_err="$(printf '%s\n%s' "$compile_err" "$line")"
        fi
    done

    # Last error/warning will end with "x errors/y warnings; remove this part."
    compile_err="$(echo "$compile_err" | sed "s/[0-9]\+ warnings\?//g")"
    compile_err="$(echo "$compile_err" | sed "s/[0-9]\+ errors\?//g")"

    # Process the last error/warning.
    if [ "$1" == 'student' ]; then
        parse_compilation_error_student "$compile_err" </dev/zero
    else
        parse_compilation_error_staff "$compile_err" </dev/zero
    fi
}

compilation_error_in_submission() {
    # Parse the amount of compilation errors and warnings.
    compile_err_count="$(compilation_error_count < "$1")"
    compile_err_count="${compile_err_count:-0}"
    compile_warn_count="$(compilation_warning_count < "$1")"
    compile_warn_count="${compile_warn_count:-0}"
    compile_errwarn_sum="$((compile_err_count + compile_warn_count))"

    # Get the correct noun.
    [ "$compile_err_count" -eq 1 ] && compile_err_noun="fout" || compile_err_noun="fouten"
    [ "$compile_warn_count" -eq 1 ] && compile_warn_noun="waarschuwing" || compile_warn_noun="waarschuwingen"

    # Build the compilation message.
    compile_message=""
    [ "$compile_err_count" -eq 0 ] || compile_message="$compile_err_count $compile_err_noun"
    [ "$compile_err_count" -ne 0 ] && [ "$compile_warn_count" -ne 0 ] && compile_message+=" en "
    [ "$compile_warn_count" -eq 0 ] || compile_message+="$compile_warn_count $compile_warn_noun"

    dodona start-judgement
    dodona start-tab -t 'Compiler'
    dodona append-message -f callout -d "Je code kon niet worden gecompileerd en bijgevolg niet worden uitgevoerd. De compiler rapporteerde $compile_message."

    parse_compilation_errors 'student' < "$1"

    dodona close-tab -b "$compile_errwarn_sum"
    dodona close-judgement -A -e 'compilation error' -h "$compile_err_count $compile_err_noun"
}

compilation_error_in_tests() {
    dodona start-judgement
    dodona start-tab -t 'Compiler'
    dodona append-message -f callout -d "Er ging iets mis tijdens het compileren van de testen voor deze oefening. Contacteer je lesgever."

    parse_compilation_errors 'staff' < "$1"

    dodona close-tab
    dodona close-judgement -A -e 'compilation error' -h 'Fout in de testen'
}


################################# [ Start run ] ################################

# Record time
start_time="$(date +"%s")"

debug after init

# Compiling judge into "build" and getting a jar in the workdir
find "$judge/src" -name '*.java' \
    | xargs javac -classpath "$judge/lib/*:/tmp/build" -d /tmp/build -sourcepath "$judge/src"
jar -cf "judge.jar" -C /tmp/build .
testlibs="$(find "$judge/lib" "$resources" -name '*.jar' | xargs echo | tr ' ' ':')"
worklibs="$(find "$workdir" -name '*.jar' | xargs echo | tr ' ' ':')"

debug compiled judge

# Compiling the workdir given code
if ! find . -name '*.java' | xargs --no-run-if-empty javac -cp ".:${worklibs}:${testlibs}" -d . -sourcepath . > "$compilation" 2>&1; then
    compilation_error_in_tests <(sed 's_.*/\([^/]*.java\)_\1_' "$compilation")
    exit 0
fi

debug compiled workdir

# Create the Input.java class, containing the submitted code
cat "$(jshon -e 'source' -u < "$config")" > "$filename"

# Compiling the user code
compile_opts="-Xlint:all"
[ "$allow_compilation_warnings" == 'true' ] || compile_opts+=' -Werror'

if ! javac -cp ".:${worklibs}" ${compile_opts} "$filename" > "$compilation" 2>&1; then
    compilation_error_in_submission "$compilation"
    exit 0
fi

debug compiled user code

# Compiling the tests
if ! find "$resources" -name '*.java' | xargs javac -cp ".:${resources}:${worklibs}:${testlibs}:judge.jar" -d . -sourcepath "$resources" > "$compilation" 2>&1; then
    compilation_error_in_tests <(sed 's_.*/\([^/]*.java\)_\1_' "$compilation")
    exit 0
fi

debug compiled tests

# Record time
compiled_time="$(date +"%s")"
compilation_time="$((compiled_time - start_time))"

# Running the tests
timeout --preserve-status "$((time_limit - compilation_time))" java -Xmx"${memory_limit}k" -cp ".:${worklibs}:${testlibs}:judge.jar" dodona.junit.JUnitJSON

debug finished
