#!/bin/sh
set -e
judge="$PWD"
for test in integration-tests/*; do
    [ -d "$test" ] || continue
    [ -n "$1" -a "$1" != "$test" ] && continue
    allow_compilation_warnings="$(jq -r '.allow_compilation_warnings == true' $test/config.json)"
    filename="$(jq -r '.filename' "$test/config.json")"
    lang="$(jq -r '.natural_language' "$test/config.json")"

    printf 'Testing %s ... ' "${test##*/}"
    workdir="$(mktemp -d)"
    cd "$workdir"

    [ -d "$judge/$test/workdir" ] && find "$judge/$test/workdir" -mindepth 1 -maxdepth 1 -exec cp -r \{\} . \;
    echo '{ "resources": "'"$judge/$test/evaluation/"'"
          , "judge": "'"$judge"'"
          , "natural_language": "'"$lang"'"
          , "workdir": "'"$workdir"'"
          , "allow_compilation_warnings": "'"$allow_compilation_warnings"'"
          , "filename": "'"$filename"'"
          , "time_limit": 30
          , "memory_limit": 1000000000
          , "source": "'"$judge/$test/submission.java"'"
          }' \
          | "$judge"/run \
          | jq --sort-keys 'if(.command == "append-message")
                then .message.description |= gsub("\n at [^\n]+\\([^)]+\\)"; "")
                else .
            end' \
          | diff "$judge/$test/result.json" -

    cd "$judge"
    rm -r "$workdir"
    echo passed
done
