name: Java

on: [push]

jobs:
  example-exercises:
    runs-on: ubuntu-latest
    container:
      image: openjdk:12-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apk add --no-cache jq=1.6-r0
    - name: Evaluate sample exercises
      run: ./integration-tests/run
