name: Java

on: [push]

jobs:
  example-exercises:
    runs-on: ubuntu-latest
    container:
      image: openjdk:12-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apk add --no-cache jq=1.6-r0
    - name: Evaluate all example exercises
      run: |
        cd testing && for d in ../examples/*; do ./clean.sh && ./test.sh $d; done || exit 1
