name: Java

on:
  push:

jobs:
  example-exercises:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:25

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apt update && apt install -y jq
    - name: Evaluate sample exercises
      run: ./integration-tests/run